name: issue reopen workflow

on:
  issues:
    types: [reopened]

jobs:
  reopen:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    steps:
      - name: notify all watchers on issue reopen
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // check if issue has the reopen label
            const issue = context.payload.issue;
            const reopenLabel = issue.labels.find(label => label.name === 'reopen');
            if (!reopenLabel) {
              console.log('Issue does not have the reopen label');
              return;
            }
            // comment on the issue and tag natalie
            const comment = `
              @some-natalie, this issue has been reopened. Please take a look.
            `;
            await github.issues.createComment({
              issue_number: issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
